# Generated by Django 5.0.2 on 2024-03-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_trend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trend',
            options={'ordering': ['-occurences']},
        ),
    ]
