# Generated by Django 5.0.2 on 2024-03-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_follow_followers_alter_follow_followings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followings',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'follower')},
        ),
    ]
